# Official docker image.
image: docker:latest

stages:
  - build
  - push_image_to_ecr

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY


build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"

push_image_to_ecr:
  stage: push_image_to_ecr
  only:
    - tags
  except:
    - master
    - develop
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}"
    - docker tag "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" "$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}"
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}"
    - $(aws ecr get-login --no-include-email --region ap-northeast-1)
    - docker tag "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:8}" 077877308982.dkr.ecr.ap-northeast-1.amazonaws.com/cqcp/web-backend/stingray:${CI_COMMIT_TAG}
    - docker push 077877308982.dkr.ecr.ap-northeast-1.amazonaws.com/cqcp/web-backend/stingray:${CI_COMMIT_TAG}
